<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $countries = [
            ['name' => 'Afghanistan'],
            ['name' => 'Albania'],
            ['name' => 'Algeria'],
            ['name' => 'Andorra'],
            ['name' => 'Angola'],
            ['name' => 'Antigua and Barbuda'],
            ['name' => 'Argentina'],
            ['name' => 'Armenia'],
            ['name' => 'Australia'],
            ['name' => 'Austria'],
            ['name' => 'Azerbaijan'],

            ['name' => 'Bahamas'],
            ['name' => 'Bahrain'],
            ['name' => 'Bangladesh'],
            ['name' => 'Barbados'],
            ['name' => 'Belarus'],
            ['name' => 'Belgium'],
            ['name' => 'Belize'],
            ['name' => 'Benin'],
            ['name' => 'Bhutan'],
            ['name' => 'Bolivia'],
            ['name' => 'Bosnia and Herzegovina'],
            ['name' => 'Botswana'],
            ['name' => 'Brazil'],
            ['name' => 'Brunei'],
            ['name' => 'Bulgaria'],
            ['name' => 'Burkina Faso'],
            ['name' => 'Burundi'],

            ['name' => 'Côte d\'Ivoire'],
            ['name' => 'Cabo Verde'],
            ['name' => 'Cambodia'],
            ['name' => 'Cameroon'],
            ['name' => 'Canada'],
            ['name' => 'Central African Republic'],
            ['name' => 'Chad'],
            ['name' => 'Chile'],
            ['name' => 'China'],
            ['name' => 'Colombia'],  
            ['name' => 'Comoros'],
            ['name' => 'Costa Rica'],
            ['name' => 'Cote d’Ivoire (Ivory Coast)'],
            ['name' => 'Croatia'],
            ['name' => 'Cuba'],
            ['name' => 'Cyprus'],
            ['name' => 'Czechia'],
            ['name' => 'Czechoslovakia'],

            ['name' => 'Democratic Republic of the Congo'],
            ['name' => 'Denmark'],
            ['name' => 'Djibouti'],
            ['name' => 'Dominica'],
            ['name' => 'Dominican Republic'],
            ['name' => 'Duchy of Parma'],

            ['name' => 'East Germany (German Democratic Republic)'],
            ['name' => 'Ecuador'],
            ['name' => 'Egypt'],
            ['name' => 'El Salvador'],
            ['name' => 'Equatorial Guinea'],
            ['name' => 'Eritrea'],
            ['name' => 'Estonia'],
            ['name' => 'Eswatini'],
            ['name' => 'Ethiopia'],

            ['name' => 'Federal Government of Germany'],
            ['name' => 'Fiji'],
            ['name' => 'Finland'],
            ['name' => 'France'],

            ['name' => 'Gabon'],
            ['name' => 'Gambia, The'],
            ['name' => 'Georgia'],
            ['name' => 'Germany'],
            ['name' => 'Ghana'],
            ['name' => 'Grand Duchy of Tuscany, The*'],
            ['name' => 'Greece'],
            ['name' => 'Grenada'],
            ['name' => 'Guatemala'],
            ['name' => 'Guinea'],
            ['name' => 'Guinea-Bissau'],
            ['name' => 'Guyana'],

            ['name' => 'Haiti'],
            ['name' => 'Hanover'],
            ['name' => 'Hanseatic Republics'],
            ['name' => 'Hawaii'],
            ['name' => 'Hesse'],
            ['name' => 'Holy See'],
            ['name' => 'Honduras'],
            ['name' => 'Hungary'],

            ['name' => 'Iceland'],
            ['name' => 'India'],
            ['name' => 'Indonesia'],
            ['name' => 'Iran'],
            ['name' => 'Iraq'],
            ['name' => 'Ireland'],
            ['name' => 'Israel'],
            ['name' => 'Italy'],

            ['name' => 'Jamaica'],
            ['name' => 'Japan'],
            ['name' => 'Jordan'],

            ['name' => 'Kazakhstan'],
            ['name' => 'Kenya'],
            ['name' => 'Kingdom of Serbia/Yugoslavia'],
            ['name' => 'Kiribati'],
            ['name' => 'Korea'],
            ['name' => 'Kosovo'],
            ['name' => 'Kuwait'],
            ['name' => 'Kyrgystan'],

            ['name' => 'Laos'],
            ['name' => 'Latvia'],
            ['name' => 'Lebanon'],
            ['name' => 'Lesotho'],
            ['name' => 'Lew Chew'],
            ['name' => 'Liberia'],
            ['name' => 'Libya'],
            ['name' => 'Liechtenstein'],
            ['name' => 'Lithuania'],
            ['name' => 'Luxembourg'],

            ['name' => 'Madagascar'],
            ['name' => 'Malawi'],
            ['name' => 'Malaysia'],
            ['name' => 'Maldives'],
            ['name' => 'Mali'],
            ['name' => 'Malta'],
            ['name' => 'Marshall Islands'],
            ['name' => 'Mauritania'],
            ['name' => 'Mauritius'],
            ['name' => 'Mecklenburg-Schwerin'],
            ['name' => 'Mecklenburg-Strelitz'],
            ['name' => 'Mexico'],
            ['name' => 'Micronesia'],
            ['name' => 'Moldova'],
            ['name' => 'Monaco'],
            ['name' => 'Mongolia'],
            ['name' => 'Montenegro'],
            ['name' => 'Morocco'],
            ['name' => 'Mozambique'],

            ['name' => 'Namibia'],
            ['name' => 'Nassau'],
            ['name' => 'Nauru'],
            ['name' => 'Nepal'],
            ['name' => 'Netherlands, The'],
            ['name' => 'New Zealand'],
            ['name' => 'Nicaragua'],
            ['name' => 'Niger'],
            ['name' => 'Nigeria'],
            ['name' => 'North German Confederation'],
            ['name' => 'North German Union'],
            ['name' => 'North Macedonia'],
            ['name' => 'Norway'],

            ['name' => 'Oldenburg'],
            ['name' => 'Oman'],
            ['name' => 'Orange Free State'],

            ['name' => 'Pakistan'],
            ['name' => 'Palau'],
            ['name' => 'Panama'],
            ['name' => 'Papal States'],
            ['name' => 'Papua New Guinea'],
            ['name' => 'Paraguay'],
            ['name' => 'Peru'],
            ['name' => 'Philippines'],
            ['name' => 'Piedmont-Sardinia'],
            ['name' => 'Poland'],
            ['name' => 'Portugal'],

            ['name' => 'Qatar'],

            ['name' => 'Republic of Genoa'],
            ['name' => 'Republic of Korea (South Korea)'],
            ['name' => 'Republic of the Congo'],
            ['name' => 'Romania'],
            ['name' => 'Russia'],
            ['name' => 'Rwanda'],

            ['name' => 'Saint Kitts and Nevis'],
            ['name' => 'Saint Lucia'],
            ['name' => 'Saint Vincent and the Grenadines'],
            ['name' => 'Samoa'],
            ['name' => 'San Marino'],
            ['name' => 'Sao Tome and Principe'],
            ['name' => 'Saudi Arabia'],
            ['name' => 'Schaumburg-Lippe'],
            ['name' => 'Senegal'],
            ['name' => 'Serbia'],
            ['name' => 'Seychelles'],
            ['name' => 'Sierra Leone'],
            ['name' => 'Singapore'],
            ['name' => 'Slovakia'],
            ['name' => 'Slovenia'],
            ['name' => 'Solomon Islands, The'],
            ['name' => 'Somalia'],
            ['name' => 'South Africa'],
            ['name' => 'South Sudan'],
            ['name' => 'Spain'],
            ['name' => 'Sri Lanka'],
            ['name' => 'Sudan'],
            ['name' => 'Suriname'],
            ['name' => 'Sweden'],
            ['name' => 'Switzerland'],
            ['name' => 'Syria'],

            ['name' => 'Tajikistan'],
            ['name' => 'Tanzania'],
            ['name' => 'Texas'],
            ['name' => 'Thailand'],
            ['name' => 'Timor-Leste'],
            ['name' => 'Togo'],
            ['name' => 'Tonga'],
            ['name' => 'Trinidad and Tobago'],
            ['name' => 'Tunisia'],
            ['name' => 'Turkey'],
            ['name' => 'Turkmenistan'],
            ['name' => 'Tuvalu'],
            ['name' => 'Two Sicilies'],

            ['name' => 'Uganda'],
            ['name' => 'Ukraine'],
            ['name' => 'Union of Soviet Socialist Republics'],
            ['name' => 'United Arab Emirates, The'],
            ['name' => 'United Kingdom, The'],
            ['name' => 'Uruguay'],
            ['name' => 'Uzbekistan'],

            ['name' => 'Vanuatu'],
            ['name' => 'Venezuela'],
            ['name' => 'Vietnam'],

            ['name' => 'Württemberg'],
            ['name' => 'Yemen'],
            ['name' => 'Zambia'],
            ['name' => 'Zimbabwe'],
        ];

        Country::insert($countries);
    }
}
