<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PhoneCode;

class PhoneCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
 
        $phonecode = [
            ['countrycode' => 'AFG','name' => 'Afghanistan','phonecode' => '+93'],
            ['countrycode' => 'ALB','name' => 'Albania','phonecode' => '+355'],
            ['countrycode' => 'DZA','name' => 'Algeria','phonecode' => '+213'],
            ['countrycode' => 'AND','name' => 'Andorra','phonecode' => '+376'],
            ['countrycode' => 'AGO','name' => 'Angola','phonecode' => '+244'],
            ['countrycode' => 'ASM','name' => 'American Samoa','phonecode' => '+1-684'],
            ['countrycode' => 'AIA','name' => 'Anguila','phonecode' => '+1-264'],
            ['countrycode' => 'ATG','name' => 'Antigua and Barbuda','phonecode' => '+1-268'],
            ['countrycode' => 'ARG','name' => 'Argentina','phonecode' => '+54'],
            ['countrycode' => 'ARM','name' => 'Armenia','phonecode' => '+374'],
            ['countrycode' => 'AUS','name' => 'Australia','phonecode' => '+61'],
            ['countrycode' => 'AUT','name' => 'Austria','phonecode' => '+43'],
            ['countrycode' => 'AZE','name' => 'Azerbaijan','phonecode' => '+994'],

            ['countrycode' => 'BHS','name' => 'Bahamas','phonecode' => '+1'],
            ['countrycode' => 'BHR','name' => 'Bahrain','phonecode' => '+973'],
            ['countrycode' => 'BGD','name' => 'Bangladesh','phonecode' => '+880'],
            ['countrycode' => 'BRB','name' => 'Barbados','phonecode' => '+1-246'],
            ['countrycode' => 'BLR','name' => 'Belarus','phonecode' => '+375'],
            ['countrycode' => 'BEL','name' => 'Belgium','phonecode' => '+32'],
            ['countrycode' => 'BLZ','name' => 'Belize','phonecode' => '+501'],
            ['countrycode' => 'BEN','name' => 'Benin','phonecode' => '+229'],
            ['countrycode' => 'BTN','name' => 'Bhutan','phonecode' => '+975'],
            ['countrycode' => 'BOL','name' => 'Bolivia','phonecode' => '+591'],
            ['countrycode' => 'BIH','name' => 'Bosnia and Herzegovina','phonecode' => '+387'],
            ['countrycode' => 'BWA','name' => 'Botswana','phonecode' => '+267'],
            ['countrycode' => 'BRA','name' => 'Brazil','phonecode' => '+55'],
            ['countrycode' => 'BRN','name' => 'Brunei','phonecode' => '+673'],
            ['countrycode' => 'BGR','name' => 'Bulgaria','phonecode' => '+359'],
            ['countrycode' => 'BFA','name' => 'Burkina Faso','phonecode' => '+226'],
            ['countrycode' => 'BDI','name' => 'Burundi','phonecode' => '+257'],

            ['countrycode' => 'CPV','name' => 'Cabo Verde','phonecode' => '+238'],
            ['countrycode' => 'KHM','name' => 'Cambodia','phonecode' => '+855'],
            ['countrycode' => 'CMR','name' => 'Cameroon','phonecode' => '+237'],
            ['countrycode' => 'CAN','name' => 'Canada','phonecode' => '+1'],
            ['countrycode' => 'CAF','name' => 'Central African Republic','phonecode' => '+236'],
            ['countrycode' => 'TCD','name' => 'Chad','phonecode' => '+235'],
            ['countrycode' => 'CHL','name' => 'Chile','phonecode' => '+56'],
            ['countrycode' => 'CHN','name' => 'China','phonecode' => '+86'],
            ['countrycode' => 'COL','name' => 'Colombia','phonecode' => '+57'],  
            ['countrycode' => 'COM','name' => 'Comoros','phonecode' => '+269'],
            ['countrycode' => 'CRI','name' => 'Costa Rica','phonecode' => '+506'],
            ['countrycode' => 'CIV','name' => 'Cote d’Ivoire','phonecode' => '+225'],
            ['countrycode' => 'HRV','name' => 'Croatia','phonecode' => '+385'],
            ['countrycode' => 'CUB','name' => 'Cuba','phonecode' => '+53'],
            ['countrycode' => 'CYP','name' => 'Cyprus','phonecode' => '+357'],
            ['countrycode' => 'CZE','name' => 'Czech Republic','phonecode' => '+420'],
            ['countrycode' => 'CSK','name' => 'Czechoslovakia','phonecode' => '+42'],

            ['countrycode' => '','name' => 'Democratic Republic of the Congo','phonecode' => '+243'],
            ['countrycode' => 'DNK','name' => 'Denmark','phonecode' => '+45'],
            ['countrycode' => 'DJI','name' => 'Djibouti','phonecode' => '+253'],
            ['countrycode' => 'DMA','name' => 'Dominica','phonecode' => '+1-767'],
            ['countrycode' => 'DOM','name' => 'Dominican Republic','phonecode' => '+1-809'],
            ['countrycode' => '','name' => 'Duchy of Parma','phonecode' => '0521'],

            ['countrycode' => '','name' => 'East Germany','phonecode' => '+37'],
            ['countrycode' => 'ECU','name' => 'Ecuador','phonecode' => '+593'],
            ['countrycode' => 'EGY','name' => 'Egypt','phonecode' => '+20'],
            ['countrycode' => 'SLV','name' => 'El Salvador','phonecode' => '+503'],
            ['countrycode' => 'GNQ','name' => 'Equatorial Guinea','phonecode' => '+240'],
            ['countrycode' => 'ERI','name' => 'Eritrea','phonecode' => '+291'],
            ['countrycode' => 'EST','name' => 'Estonia','phonecode' => '+372'],
            ['countrycode' => '','name' => 'Eswatini','phonecode' => '+268'],
            ['countrycode' => 'ETH','name' => 'Ethiopia(excludes Eritrea)','phonecode' => '+251'],
            ['countrycode' => 'ETF','name' => 'Ethiopia(includes Eritrea)','phonecode' => '+251'],

            ['countrycode' => 'FLK','name' => 'Falakland Island','phonecode' => '+500'],
            ['countrycode' => 'Fro','name' => 'Faeroe Island','phonecode' => '+298'],
            ['countrycode' => 'FJI','name' => 'Fiji','phonecode' => '+679'],
            ['countrycode' => 'FIN','name' => 'Finland','phonecode' => '+358'],
            ['countrycode' => 'FRA','name' => 'France','phonecode' => '+33'],

            ['countrycode' => 'GAB','name' => 'Gabon','phonecode' => '+241'],
            ['countrycode' => 'GMB','name' => 'Gambia, The','phonecode' => '+220'],
            ['countrycode' => 'GEO','name' => 'Georgia','phonecode' => '+995'],
            ['countrycode' => 'DEU','name' => 'Germany','phonecode' => '+49'],
            ['countrycode' => 'GHA','name' => 'Ghana','phonecode' => '+233'],
            ['countrycode' => '','name' => 'Grand Duchy of Tuscany, The','phonecode' => '+39'],
            ['countrycode' => 'GRC','name' => 'Greece','phonecode' => '+30'],
            ['countrycode' => 'GRD','name' => 'Grenada','phonecode' => '+1-473'],
            ['countrycode' => 'GTM','name' => 'Guatemala','phonecode' => '+502'],
            ['countrycode' => 'GIN','name' => 'Guinea','phonecode' => '+224'],
            ['countrycode' => 'GNB','name' => 'Guinea-Bissau','phonecode' => '+224'],
            ['countrycode' => 'GUY','name' => 'Guyana','phonecode' => '+592'],

            ['countrycode' => 'HTI','name' => 'Haiti','phonecode' => '+509'],
            ['countrycode' => '','name' => 'Hanover','phonecode' => '+49-511'],
            ['countrycode' => '','name' => 'Hanseatic Republics','phonecode' => '0451'],
            ['countrycode' => '','name' => 'Hawaii','phonecode' => ''],
            ['countrycode' => '','name' => 'Hesse','phonecode' => '+49'],
            ['countrycode' => 'VAT','name' => 'Holy See','phonecode' => '+379'],
            ['countrycode' => 'HND','name' => 'Honduras','phonecode' => '+504'],
            ['countrycode' => 'HUN','name' => 'Hungary','phonecode' => '36'],

            ['countrycode' => 'ISL','name' => 'Iceland','phonecode' => '+345'],
            ['countrycode' => 'IND','name' => 'India','phonecode' => '+91'],
            ['countrycode' => 'IDN','name' => 'Indonesia','phonecode' => '+62'],
            ['countrycode' => 'IRN','name' => 'Iran','phonecode' => '+98'],
            ['countrycode' => 'IRQ','name' => 'Iraq','phonecode' => '+964'],
            ['countrycode' => 'IRL','name' => 'Ireland','phonecode' => '+353'],
            ['countrycode' => 'ISR','name' => 'Israel','phonecode' => '+972'],
            ['countrycode' => 'ITA','name' => 'Italy','phonecode' => '+39'],

            ['countrycode' => 'JAM','name' => 'Jamaica','phonecode' => '+1'],
            ['countrycode' => 'JPN','name' => 'Japan','phonecode' => '+81'],
            ['countrycode' => 'JOR','name' => 'Jordan','phonecode' => '+962'],

            ['countrycode' => 'KAZ','name' => 'Kazakhstan','phonecode' => '+7'],
            ['countrycode' => 'KEN','name' => 'Kenya','phonecode' => '+254'],
            ['countrycode' => '','name' => 'Kingdom of Serbia/Yugoslavia','phonecode' => '+381'],
            ['countrycode' => 'KIR','name' => 'Kiribati','phonecode' => '+686'],
            ['countrycode' => 'PRK','name' => 'Korea','phonecode' => '+82'],
            ['countrycode' => '','name' => 'Kosovo','phonecode' => '+383'],
            ['countrycode' => 'KWT','name' => 'Kuwait','phonecode' => '+965'],
            ['countrycode' => '','name' => 'Kyrgystan','phonecode' => '+996'],

            ['countrycode' => 'LAO','name' => 'Laos','phonecode' => '+856'],
            ['countrycode' => 'LVA','name' => 'Latvia','phonecode' => '+371'],
            ['countrycode' => 'LBN','name' => 'Lebanon','phonecode' => '+961'],
            ['countrycode' => 'LSO','name' => 'Lesotho','phonecode' => '+996'],
            ['countrycode' => '','name' => 'Lew Chew','phonecode' => '+64'],
            ['countrycode' => 'LBR','name' => 'Liberia','phonecode' => '+231'],
            ['countrycode' => 'LBY','name' => 'Libya','phonecode' => '+218'],
            ['countrycode' => 'LIE','name' => 'Liechtenstein','phonecode' => '+423'],
            ['countrycode' => 'LTU','name' => 'Lithuania','phonecode' => '+370'],
            ['countrycode' => 'LUX','name' => 'Luxembourg','phonecode' => '+352'],

            ['countrycode' => 'MWI','name' => 'Malawi','phonecode' => '+265'],
            ['countrycode' => 'MDG','name' => 'Madagascar','phonecode' => '+261'],
            ['countrycode' => 'MYS','name' => 'Malaysia','phonecode' => '+60'],
            ['countrycode' => 'MDV','name' => 'Maldives','phonecode' => '+960'],
            ['countrycode' => 'MLI','name' => 'Mali','phonecode' => '+223'],
            ['countrycode' => 'MLT','name' => 'Malta','phonecode' => '+356'],
            ['countrycode' => 'MHL','name' => 'Marshall Islands','phonecode' => '+692'],
            ['countrycode' => 'MRT','name' => 'Mauritania','phonecode' => '+222'],
            ['countrycode' => 'MUS','name' => 'Mauritius','phonecode' => '+230'],
            ['countrycode' => 'MEX','name' => 'Mexico','phonecode' => '+52'],
            ['countrycode' => 'FSM','name' => 'Micronesia','phonecode' => '+691'],
            ['countrycode' => 'MDA','name' => 'Moldova','phonecode' => '+373'],
            ['countrycode' => 'MCO','name' => 'Monaco','phonecode' => '+377'],
            ['countrycode' => 'MNG','name' => 'Mongolia','phonecode' => '+976'],
            ['countrycode' => 'MSR','name' => 'Montserrat','phonecode' => '+1-664'],
            ['countrycode' => 'MAR','name' => 'Morocco','phonecode' => '+212'],
            ['countrycode' => 'MOZ','name' => 'Mozambique','phonecode' => '+258'],
            ['countrycode' => 'MMR','name' => 'Myanmar','phonecode' => '+95'],

            ['countrycode' => 'NAM','name' => 'Namibia','phonecode' => '+264'],
            ['countrycode' => 'NRU','name' => 'Nauru','phonecode' => '+674'],
            ['countrycode' => 'NPL','name' => 'Nepal','phonecode' => '+977'],
            ['countrycode' => 'NLD','name' => 'Netherlands, The','phonecode' => '+31'],
            ['countrycode' => 'NZL','name' => 'New Zealand','phonecode' => '+64'],
            ['countrycode' => 'NIC','name' => 'Nicaragua','phonecode' => '+505'],
            ['countrycode' => 'NER','name' => 'Niger','phonecode' => '+227'],
            ['countrycode' => 'NGA','name' => 'Nigeria','phonecode' => '+234'],
            ['countrycode' => 'NOR','name' => 'Norway','phonecode' => '+47'],

            ['countrycode' => 'OMN','name' => 'Oman','phonecode' => '+968'],

            ['countrycode' => 'PAK','name' => 'Pakistan','phonecode' => '+92'],
            ['countrycode' => 'PLW','name' => 'Palau','phonecode' => '+680'],
            ['countrycode' => 'PAN','name' => 'Panama','phonecode' => '+507'],
            ['countrycode' => 'PNG','name' => 'Papua New Guinea','phonecode' => '+675'],
            ['countrycode' => 'PRY','name' => 'Paraguay','phonecode' => '+47'],
            ['countrycode' => 'PER','name' => 'Peru','phonecode' => '+51'],
            ['countrycode' => 'PHL','name' => 'Philippines','phonecode' => '+63'],
            ['countrycode' => 'POL','name' => 'Poland','phonecode' => '+48'],
            ['countrycode' => 'PRT','name' => 'Portugal','phonecode' => '+351'],

            ['countrycode' => 'QAT','name' => 'Qatar','phonecode' => '+974'],

            ['countrycode' => 'ROM','name' => 'Romania','phonecode' => '+40'],
            ['countrycode' => 'RUS','name' => 'Russia','phonecode' => '+7'],
            ['countrycode' => 'RWA','name' => 'Rwanda','phonecode' => '+250'],

            ['countrycode' => 'KN1','name' => 'Saint Kitts and Nevis','phonecode' => '+1'],
            ['countrycode' => 'LCA','name' => 'Saint Lucia','phonecode' => '+1-758'],
            ['countrycode' => '','name' => 'Saint Vincent and the Grenadines','phonecode' => '+1-784'],
            ['countrycode' => 'WSM','name' => 'Samoa','phonecode' => '+685'],
            ['countrycode' => 'SMR','name' => 'San Marino','phonecode' => '+378'],
            ['countrycode' => 'STP','name' => 'Sao Tome and Principe','phonecode' => '+239'],
            ['countrycode' => 'SAU','name' => 'Saudi Arabia','phonecode' => '+966'],
            ['countrycode' => 'SEN','name' => 'Senegal','phonecode' => '+221'],
            ['countrycode' => '','name' => 'Serbia','phonecode' => '+381'],
            ['countrycode' => 'SYC','name' => 'Seychelles','phonecode' => '+248'],
            ['countrycode' => 'SLE','name' => 'Sierra Leone','phonecode' => '+232'],
            ['countrycode' => 'SGP','name' => 'Singapore','phonecode' => '+65'],
            ['countrycode' => 'SVK','name' => 'Slovakia','phonecode' => '+421'],
            ['countrycode' => 'SVN','name' => 'Slovenia','phonecode' => '+386'],
            ['countrycode' => 'SLB','name' => 'Solomon Islands, The','phonecode' => '+677'],
            ['countrycode' => 'SOM','name' => 'Somalia','phonecode' => '+252'],
            ['countrycode' => 'ZAF','name' => 'South Africa','phonecode' => '+27'],
            ['countrycode' => 'SDN','name' => 'Sudan','phonecode' => '+249'],
            ['countrycode' => 'ESP','name' => 'Spain','phonecode' => '+34'],
            ['countrycode' => 'LKA','name' => 'Sri Lanka','phonecode' => '+94'],
            ['countrycode' => 'SUR','name' => 'Suriname','phonecode' => '+597'],
            ['countrycode' => 'SWE','name' => 'Sweden','phonecode' => '+46'],
            ['countrycode' => 'CHE','name' => 'Switzerland','phonecode' => '+41'],
            ['countrycode' => 'SYR','name' => 'Syria','phonecode' => '+963'],

            ['countrycode' => 'TJK','name' => 'Tajikistan','phonecode' => '+992'],
            ['countrycode' => 'TZA','name' => 'Tanzania','phonecode' => '+255'],
            ['countrycode' => '','name' => 'Texas','phonecode' => '+713'],
            ['countrycode' => 'THA','name' => 'Thailand','phonecode' => '+66'],
            ['countrycode' => '','name' => 'Timor-Leste','phonecode' => '+670'],
            ['countrycode' => 'TGO','name' => 'Togo','phonecode' => '+228'],
            ['countrycode' => 'TON','name' => 'Tonga','phonecode' => '+676'],
            ['countrycode' => 'TTO','name' => 'Trinidad and Tobago','phonecode' => '+1-868'],
            ['countrycode' => 'TUN','name' => 'Tunisia','phonecode' => '+216'],
            ['countrycode' => 'TUR','name' => 'Turkey','phonecode' => '+90'],
            ['countrycode' => 'TKM','name' => 'Turkmenistan','phonecode' => '+993'],
            ['countrycode' => 'TUV','name' => 'Tuvalu','phonecode' => '+688'],

            ['countrycode' => 'UGA','name' => 'Uganda','phonecode' => '+256',],
            ['countrycode' => 'UKR','name' => 'Ukraine','phonecode' => '+380',],
            ['countrycode' => 'USA','name' => 'United States','phonecode' => '+1',],
            ['countrycode' => 'ARE','name' => 'United Arab Emirates, The','phonecode' => '+971',],
            ['countrycode' => 'GBR','name' => 'United Kingdom, The','phonecode' => '+44',],
            ['countrycode' => 'URY','name' => 'Uruguay','phonecode' => '+598',],
            ['countrycode' => 'UZB','name' => 'Uzbekistan','phonecode' => '+998',],

            ['countrycode' => 'VUT','name' => 'Vanuatu','phonecode' => '+678',],
            ['countrycode' => 'VEN','name' => 'Venezuela','phonecode' => '+58',],
            ['countrycode' => 'VNM','name' => 'Vietnam','phonecode' => '+84',],

            ['countrycode' => '','name' => 'Württemberg','phonecode' => '7656',],

            ['countrycode' => 'YEM','name' => 'Yemen','phonecode' => '+967',],

            ['countrycode' => 'ZMB','name' => 'Zambia','phonecode' => '+260',],
            ['countrycode' => 'ZWE','name' => 'Zimbabwe','phonecode' => '+263',],
        ];

        PhoneCode::insert($phonecode);
    }
}
